export const GET_REGION_REQUEST = "GET_REGION_REQUEST";
export const GET_REGION_SUCCESS = "GET_REGION_SUCCESS";
export const GET_REGION_FAIL = "GET_REGION_FAIL";
export const GET_AREA_REQUEST = "GET_AREA_REQUEST";
export const GET_AREA_SUCCESS = "GET_AREA_SUCCESS";
export const GET_AREA_FAIL = "GET_AREA_FAIL";